name: Steam queue bot

on:
  push:
  schedule:
    - cron:  '0 01 * * *'
  workflow_dispatch:

jobs:
  queue-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 
        architecture: 'x64' 
    - name: Run queue bot
      run: python queue-bot.py
      env:
        STEAM_COOKIE: ${{ secrets.STEAM_COOKIE }}